// Auto-generated by scripts/extract_schematic_depths.py. Do not edit manually.
export interface SchematicComponentRange {
  name: string;
  top_m: number;
  bottom_m: number;
  length_m: number;
}

export interface SchematicDepthEntry {
  source_file: string;
  source_uwi: string | null;
  match_tokens: string[];
  total_depth_m: number | null;
  pump: SchematicComponentRange | null;
  slotted_tag_bar: SchematicComponentRange | null;
  no_turn_tool: SchematicComponentRange | null;
  wellfi_tool: SchematicComponentRange | null;
}

export const SCHEMATIC_DEPTHS: SchematicDepthEntry[] = [
  {
    "source_file": "100012908218W5 Downhole Well Profile.pdf",
    "source_uwi": "100/01-29-082-18W5",
    "match_tokens": [
      "100012908218W5"
    ],
    "total_depth_m": 2427.0,
    "pump": {
      "name": "Pump Section",
      "top_m": 831.72,
      "bottom_m": 839.62,
      "length_m": 7.9
    },
    "slotted_tag_bar": {
      "name": "Slotted Tag Bar",
      "top_m": 839.75,
      "bottom_m": 840.67,
      "length_m": 0.92
    },
    "no_turn_tool": {
      "name": "No Turn Tool",
      "top_m": 840.67,
      "bottom_m": 841.28,
      "length_m": 0.61
    },
    "wellfi_tool": null
  },
  {
    "source_file": "100141808317W5 DH Schematic.pdf",
    "source_uwi": "100/14-18-083-17W5",
    "match_tokens": [
      "100141808317W5"
    ],
    "total_depth_m": 2434.0,
    "pump": {
      "name": "Pump Section",
      "top_m": 801.57,
      "bottom_m": 809.67,
      "length_m": 8.1
    },
    "slotted_tag_bar": {
      "name": "Slotted Tag Bar",
      "top_m": 809.67,
      "bottom_m": 810.46,
      "length_m": 0.79
    },
    "no_turn_tool": {
      "name": "No Turn Tool",
      "top_m": 810.46,
      "bottom_m": 811.06,
      "length_m": 0.6
    },
    "wellfi_tool": null
  }
];
