/**
 * FormationOverlay — Native Mapbox GL layers for subsurface formation
 * visualization using depth contour rings, geological boundary lines,
 * and formation labels.
 *
 * "Boreal Terrain" theme: warm earth tones that pop against the green-
 * dominated boreal satellite imagery of the Peace River region.
 * Bluesky = amber-gold (glauconitic sandstone), Clearwater = copper
 * (ironstone/shale). Follows USGS color conventions for Cretaceous fmns.
 *
 * Depth contours are generated by interpolating the formation boundary
 * toward its centroid at 5 levels, creating a topographic bowl effect
 * that communicates formation depth beneath the surface.
 */
import type { Map as MapboxMap } from 'mapbox-gl';
import { FORMATION_POLYGONS, type FormationPolygon } from '@/lib/formationData';

// ─── Layer & source IDs ────────────────────────────────────────────────────
const SRC_FILLS = 'formation-fills-src';
const SRC_BOUNDARY = 'formation-boundary-src';

const LAYER_FILL = 'formation-fill';
const LAYER_CONTOUR = 'formation-contour-lines';
const LAYER_BORDER_GLOW = 'formation-border-glow';
const LAYER_BORDER = 'formation-border';
const LAYER_LABEL = 'formation-labels';

const ALL_LAYERS = [LAYER_LABEL, LAYER_BORDER, LAYER_BORDER_GLOW, LAYER_CONTOUR, LAYER_FILL];
const ALL_SOURCES = [SRC_FILLS, SRC_BOUNDARY];

// ─── Depth contour config ──────────────────────────────────────────────────
// Each level is a fraction of distance from centroid to boundary.
// 1.0 = full boundary, 0.2 = 20% toward centroid (deepest core).
const CONTOUR_LEVELS = [1.0, 0.80, 0.60, 0.40, 0.20];

// ─── Helpers ───────────────────────────────────────────────────────────────

function computeCentroid(boundary: number[][]): [number, number] {
  const ring = boundary.slice(0, -1); // exclude closing duplicate
  const lng = ring.reduce((sum, p) => sum + p[0], 0) / ring.length;
  const lat = ring.reduce((sum, p) => sum + p[1], 0) / ring.length;
  return [lng, lat];
}

function interpolateRing(
  boundary: number[][],
  centroid: [number, number],
  fraction: number,
): number[][] {
  const ring = boundary.map(([lng, lat]) => [
    centroid[0] + (lng - centroid[0]) * fraction,
    centroid[1] + (lat - centroid[1]) * fraction,
  ]);
  // Ensure closed ring
  if (
    ring.length > 0 &&
    (ring[0][0] !== ring[ring.length - 1][0] ||
      ring[0][1] !== ring[ring.length - 1][1])
  ) {
    ring.push([ring[0][0], ring[0][1]]);
  }
  return ring;
}

// ─── GeoJSON builders ──────────────────────────────────────────────────────

function buildDepthContoursGeoJSON(): GeoJSON.FeatureCollection {
  const features: GeoJSON.Feature[] = [];

  for (const fp of FORMATION_POLYGONS) {
    const centroid = computeCentroid(fp.boundary);

    for (let i = 0; i < CONTOUR_LEVELS.length; i++) {
      const ring = interpolateRing(fp.boundary, centroid, CONTOUR_LEVELS[i]);

      features.push({
        type: 'Feature',
        geometry: { type: 'Polygon', coordinates: [ring] },
        properties: {
          id: fp.id,
          name: fp.name,
          depth_level: i,
        },
      });
    }
  }

  return { type: 'FeatureCollection', features };
}

function buildBoundaryGeoJSON(): GeoJSON.FeatureCollection {
  return {
    type: 'FeatureCollection',
    features: FORMATION_POLYGONS.map((fp: FormationPolygon) => ({
      type: 'Feature' as const,
      geometry: { type: 'Polygon' as const, coordinates: [fp.boundary] },
      properties: {
        id: fp.id,
        name: fp.name,
        depth_m: fp.depth_m,
        thickness_m: fp.thickness_m,
        label: `${fp.name.toUpperCase()}\n${fp.depth_m}m TVD`,
      },
    })),
  };
}

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Add all formation layers to the map.
 * Call this in the map load handler BEFORE the DLS grid layers
 * so formations render beneath the grid.
 */
export function addFormationLayers(map: MapboxMap): void {
  map.addSource(SRC_FILLS, { type: 'geojson', data: buildDepthContoursGeoJSON() });
  map.addSource(SRC_BOUNDARY, { type: 'geojson', data: buildBoundaryGeoJSON() });

  // ── Depth contour fills ──
  // Stacked polygons from outer (lightest) to inner (darkest).
  // fill-sort-key ensures correct rendering order.
  map.addLayer({
    id: LAYER_FILL,
    type: 'fill',
    source: SRC_FILLS,
    layout: {
      'fill-sort-key': ['get', 'depth_level'] as unknown as number,
    },
    paint: {
      'fill-color': [
        'case',
        ['==', ['get', 'id'], 'bluesky'],
        [
          'interpolate', ['linear'], ['get', 'depth_level'],
          0, 'rgba(217, 158, 46, 0.07)',
          4, 'rgba(217, 158, 46, 0.28)',
        ],
        ['==', ['get', 'id'], 'clearwater'],
        [
          'interpolate', ['linear'], ['get', 'depth_level'],
          0, 'rgba(196, 112, 52, 0.09)',
          4, 'rgba(196, 112, 52, 0.30)',
        ],
        'rgba(140, 120, 80, 0.08)',
      ] as unknown as string,
      'fill-opacity': 1,
      'fill-opacity-transition': { duration: 500, delay: 0 },
    },
  });

  // ── Depth contour lines (inner rings only — dashed, subtle) ──
  map.addLayer({
    id: LAYER_CONTOUR,
    type: 'line',
    source: SRC_FILLS,
    filter: ['>', ['get', 'depth_level'], 0],
    paint: {
      'line-color': [
        'match', ['get', 'id'],
        'bluesky', '#EAC54F',
        'clearwater', '#E8985A',
        '#B8A080',
      ] as unknown as string,
      'line-width': 0.5,
      'line-opacity': 0.2,
      'line-opacity-transition': { duration: 500, delay: 0 },
      'line-dasharray': [3, 3],
    },
  });

  // ── Boundary glow (wide, blurred line) ──
  map.addLayer({
    id: LAYER_BORDER_GLOW,
    type: 'line',
    source: SRC_BOUNDARY,
    paint: {
      'line-color': [
        'match', ['get', 'id'],
        'bluesky', '#D4A017',
        'clearwater', '#C47034',
        '#B8A080',
      ] as unknown as string,
      'line-width': 10,
      'line-opacity': 0.15,
      'line-opacity-transition': { duration: 500, delay: 0 },
      'line-blur': 6,
    },
  });

  // ── Boundary line (crisp, geological) ──
  map.addLayer({
    id: LAYER_BORDER,
    type: 'line',
    source: SRC_BOUNDARY,
    paint: {
      'line-color': [
        'match', ['get', 'id'],
        'bluesky', '#D4A017',
        'clearwater', '#C47034',
        '#B8A080',
      ] as unknown as string,
      'line-width': 1.8,
      'line-opacity': 0.7,
      'line-opacity-transition': { duration: 500, delay: 0 },
    },
  });

  // ── Formation labels ──
  map.addLayer({
    id: LAYER_LABEL,
    type: 'symbol',
    source: SRC_BOUNDARY,
    layout: {
      'text-field': ['get', 'label'],
      'text-size': 12,
      'text-font': ['DIN Pro Medium', 'Arial Unicode MS Bold'],
      'text-line-height': 1.5,
      'text-anchor': 'center',
      'text-justify': 'center',
      'text-letter-spacing': 0.08,
      'text-allow-overlap': false,
    },
    paint: {
      'text-color': [
        'match', ['get', 'id'],
        'bluesky', '#EAC54F',
        'clearwater', '#E8985A',
        '#FAF5EB',
      ] as unknown as string,
      'text-halo-color': 'rgba(0, 0, 0, 0.85)',
      'text-halo-width': 1.5,
      'text-opacity': 0.85,
      'text-opacity-transition': { duration: 500, delay: 0 },
    },
  });
}

/**
 * Remove all formation layers and sources from the map.
 */
export function removeFormationLayers(map: MapboxMap): void {
  for (const id of ALL_LAYERS) {
    if (map.getLayer(id)) map.removeLayer(id);
  }
  for (const id of ALL_SOURCES) {
    if (map.getSource(id)) map.removeSource(id);
  }
}

/**
 * Smoothly fade formation layers in/out using opacity transitions.
 */
export function setFormationVisibility(map: MapboxMap, visible: boolean): void {
  if (map.getLayer(LAYER_FILL)) {
    map.setPaintProperty(LAYER_FILL, 'fill-opacity', visible ? 1 : 0);
  }
  if (map.getLayer(LAYER_CONTOUR)) {
    map.setPaintProperty(LAYER_CONTOUR, 'line-opacity', visible ? 0.2 : 0);
  }
  if (map.getLayer(LAYER_BORDER_GLOW)) {
    map.setPaintProperty(LAYER_BORDER_GLOW, 'line-opacity', visible ? 0.15 : 0);
  }
  if (map.getLayer(LAYER_BORDER)) {
    map.setPaintProperty(LAYER_BORDER, 'line-opacity', visible ? 0.7 : 0);
  }
  if (map.getLayer(LAYER_LABEL)) {
    map.setPaintProperty(LAYER_LABEL, 'text-opacity', visible ? 0.85 : 0);
  }
}
